### PR TITLE
Fix/fix incorrect aliasing

### LINKED ISSUE #57: Incorrect AS aliasing in snowplow_mobile_base_events_this_run.sql
## Describe the bug

In the geo context columns in the [events_this_run.sql file in Databricks](https://github.com/snowplow/dbt-snowplow-mobile/blob/main/models/base/scratch/databricks/snowplow_mobile_base_events_this_run.sql) there are 3 different erroneous `AS AS` trying to alias column names which fail to run successfully

## Screenshots and log output
CleanShot 2023-01-11 at 15 58 51

## System information
**The contents of your `packages.yml` file:**
```yml
# contents goes here
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ x] databricks
- [ ] other (specify: ____________)

### PR DESCRIPTION
**Pull request by rlh1994**
## Description & motivation
Fixes #57 by removing the double AS's.

Added integration tests for the geolocation stuff. It also adds in a temporary overwrite to the `equality` test to allow for precision differneces in floats. I have raised it with dbt_utils to look at getting it added in there, if not we can add it longer term in our utils package. https://github.com/dbt-labs/dbt-utils/issues/757 

Also adds the new docs pages action - we will need to get the pages branch changed before this is released.

## Checklist
- [x] I have verified that these changes work locally
- [NA] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [NA] I have raised a [documentation](https://github.com/snowplow/documentation) PR if applicable (Link here if required)

### CODE REVIEW

File: integration_tests/models/source/snowflake/snowplow_mobile_events_stg.sql [hunk 1]
```diff
@@ -417,7 +426,8 @@ select
...
-    parse_json('[{"firstEventId":"'||firstEventId||'", "previousSessionId":"'||previousSessionId||'", "sessionId":"'||sessionId||'", "sessionIndex":"'||sessionIndex||'", "userId":"'||userId||'", "eventIndex":"'||eventIndex||'", "storageMechanism":"'||storageMechanism||'", "firstEventTimestamp":"'||firstEventTimestamp||'"}]' ) as contexts_com_snowplowanalytics_snowplow_client_session_1
+    parse_json('[{"firstEventId":"'||firstEventId||'", "previousSessionId":"'||previousSessionId||'", "sessionId":"'||sessionId||'", "sessionIndex":"'||sessionIndex||'", "userId":"'||userId||'", "eventIndex":"'||eventIndex||'", "storageMechanism":"'||storageMechanism||'", "firstEventTimestamp":"'||firstEventTimestamp||'"}]' ) as contexts_com_snowplowanalytics_snowplow_client_session_1,
+    to_variant([OBJECT_CONSTRUCT_KEEP_NULL('latitude', latitude, 'longitude', longitude, 'latitudeLongitudeAccuracy', latitudeLongitudeAccuracy, 'altitude', altitude, 'altitudeAccuracy', altitudeAccuracy, 'bearing', bearing,'speed', speed,'timestamp', timestamp)]) as contexts_com_snowplowanalytics_snowplow_geolocation_context_1
```
Comment (emielver) [inline integration_tests/models/source/snowflake/snowplow_mobile_events_stg.sql:430]: Would `parse_json` not work here? Or otherwise should we change the other contexts to use `to_variant`? Or is that not needed because the `client_session` is never NULL?

File: integration_tests/macros/equality.sql [hunk 2]
```diff
@@ -0,0 +1,96 @@
+{% test equality(model, compare_model, compare_columns=None, precision = None) %}
```
Comment (emielver) [inline integration_tests/macros/equality.sql:1]: Is it worth putting this in `snowplow_utils` properly within this release? So that other packages can also leverage this?

**Review by emielver — COMMENTED** [review]
LGTM, couple of lingering questions though

File: integration_tests/macros/equality.sql (hunk 2 above)
Comment (rlh1994) [reply integration_tests/macros/equality.sql:1]: I nearly did, but I'm hoping it will get added to dbt_utils, or at least they'll say that they aren't going to add it. Once they respond to the issue we can make a decision after that but leave it here for now?

**Review by emielver — APPROVED** [review]
LGTM!
