### PR TITLE
Release snowplow-mobile v0.3.1

### LINKED ISSUE #18: Fix user_stitching bug with differing column lengths
### Describe the bug
The stitched_user_id column is being created as a varchar column of the same length as device_user_id. If the user_id is longer than the device_user_id then this leads to errors since we later update the value of stitched_user_id to that of user_id.

### Steps to reproduce
Create dummy data where the domain_userid is a VARCHAR(6) and the user_id is VARCHAR(12).

### PR DESCRIPTION
**Pull request by emielver**
## Description & motivation
- Fix user_stitching bug with differing column lengths (Close #18)

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)

### CODE REVIEW

File: models/sessions/scratch/snowplow_mobile_sessions_this_run.sql [hunk 1]
```diff
@@ -28,9 +28,9 @@ select
 
   {% if var('snowplow__session_stitching') %}
     -- updated with mapping as part of post hook on derived sessions table
-    cast(es.device_user_id as {{dbt_utils.type_string() }}) as stitched_user_id,
+    cast(es.device_user_id as {{snowplow_utils.type_string(4096) }}) as stitched_user_id,
```
Comment (bill-warner) [inline models/sessions/scratch/snowplow_mobile_sessions_this_run.sql:31]: Can we apply the same macro to the `snowplow_mobile_incremental_manifest` as you have done in the web release?

**Review by bill-warner — APPROVED** [review]
Looks good. Would be good to clean up the manifest model too with that macro.
